### ISSUE TITLE
Image link issues in admin

### ISSUE THREAD

**Issue by gkaya** [blogifierdotnet/Blogifier.SPA#2]
Hi,

I see broken images in various parts of admin.

I.e.  on attempt to change the avatar of a profile. (let's say admin)
File manager pops up, the listed images are not shown correctly.

When I inspect and check the image source, I see following:
domain/domain/wwwroot/data/admin/2020/5/myimage

the correct image location is:
domain/data/admin/2020/5/myimage

Similar problems occur in cover image update of the post entries.

Is there a global configuration that I overlooked to configure or is it an issue at Filemanager js file?

Thanks
Gokhan

**Comment by rxtur** [comment]
You probably running your app in sub-folder, like `http://my.app/sub`. If so, you'll need to update base URL in the `Index.html` from `<base href="/">` to `<base href="/sub/">` and then re-build your theme.

This is one of the unfortunate issues with SPA frameworks, they all rely on base URL and don't let to change it on-the-fly or make it configurable.

**Comment by gkaya** [comment]
Hi, 

Thanks for the update but no I'm not using any sub-folder and using the standard theme. (as we agreed previously other themes are not fully functional at the moment).

It has SQL Server setup, freshly compiled and installed from today's master copy, nothing is altered.
I have created test accounts:
http://www.sinesanat.com
testuser/testuser
testadmin/testadmin

PS: at physical file system, files are under a directory wwwroot. There is another wwwroot inside the Blogifier folder. If there is a find&concatenate operation depending on wwwroot this might confuse the logic.  Just saying if that could be helpful. 

Best regards
Gokhan

**Comment by gkaya** [comment]
Hi,

I tested my theory about wwwroot, I moved the Blogifier subfolder to a different folder where there will be no wwwroot in the folder hierarchy. 

It helped a little bit. I.e. the images where broken in the filemanager now they are shown.
Also uploaded cover images for the posts listed on main page is properly shown now. 

Following problems seem to persist;
- On main page cover image is correctly shown but broken on the post page. (again image src is wrong)
- Same problem for avatars, broken.
- Although I can see the images that I upload now, when I upload a file, two copies are added and listed in the file manager.

Again fresh installation from today's copy. 

Best regards
Gokhan

**Comment by rxtur** [comment]
Try again, not sure because I can't re-create your setup, but it works fine when I run it from folder like "c:/wwwroot/blog/Blogifier.SPA".

**Comment by gkaya** [comment]
Hi,

Thanks for the update, I made a new installation from the recent copy and there seems to be an improvement.

On uploading a file there was 2 copies shown in the file manager, that is fixed, works as expected.

I can see the images successfully on the main page:
http://www.sinesanat.com/

but on post details, no image is shown:
http://www.sinesanat.com/posts/recent-test-post
Also updated avatar is not visible on the same page too.

the account was testuser/testuser if you want to try.

BR
Gokhan

**Comment by rxtur** [comment]
The copies were not duplicates, it was large image and thumbnail generated for it. I turned this feature off for SPA app.

With remaining issue, I can't recreate it - not sure why it does it in your case. Something in IIS or something else unique to your setup - these things need to be reproducible to fix.

**Comment by gkaya** [comment]
I think It is related with the file size or file name.

After some testing I found out that small sized images that I download from internet works but an image file shot by my phone doesn't work.
I'm attaching the file. 


![2018-06-30 11 16 40](https://user-images.githubusercontent.com/5153295/81900179-013b9780-95c5-11ea-9b59-3ad60c3d12f9.jpg)

Everything is standard by the way.
c:\inetpub\wwwroot was the default folder of IIS.
This is an image from Samsung phone without changing anything, even the filename.

BR
Gokhan

**Comment by rxtur** [comment]
I'll add error handling to throw if image can't be saved, but there 2 things to consider:
1. There should be setting in `web.config` that sets max size for uploads, and with hosting it can even be outside of your control - set in machine config overriding your app config.
2. I don't think it is a good idea to upload huge images to website anyways, they should be optimized for the web. 

I understand it is convenient to just shoot a photo and send it to the post, maybe need to look into ways to optimize it on-the-fly, kind of like right now there thumbnail generated for large images, maybe there a way to shrink it to reasonable size before saving.

**Comment by gkaya** [comment]
Hi,

Yes an error handling would be nice. 
It's good to know that this can be configured over web.config easily, so each blog owner can set their max limit. 

I do think an on the fly conversion is needed. System.Drawing would do the job but might create some dependencies.  ImageSharp library seems to be standalone and also has .net Core support, it could be a better choice. 
If you would add this feature please make sure aspect ratio will not be broken. (usually the smallest corner is taken as baseline and the other corner is reduced respectively to aspect ratio)

I didn't understand the use-case of thumbnails, what are they used for?

Resize would be nice, keeping the original image as a secondary option in the filemanager, why not?
But there needs to be an easy way to distinguish them. (i.e. file name in capital letters appearing on hover?)

Best regards
Gokhan
