### ISSUE TITLE
Standard user - profile update

### ISSUE THREAD

**Issue by gkaya** [blogifierdotnet/Blogifier.SPA#3]
Hi,

Bio update (only text, or text + avatar update) gives 401 error when tried with normal user. 
Same functionality works for admin user. 

Best regards
Gokhan

**Comment by gkaya** [comment]
Just to give more details, It is SQL Server setup.
Freshly compiled and installed from today's copy. 

I don't have anything on the site yet so created test users if you wish to observe.

http://www.sinesanat.com
testuser/testuser
testadmin/testadmin

as you would see BIO update on admin works fine but gives error on normal user.

I'll delete the accounts later. 

BR
Gokhan

**Comment by rxtur** [comment]
Should work with latest update
